const quoteBase=window.JMY_SUPABASE_URL,quoteKey=window.JMY_SUPABASE_PUBLISHABLE_KEY,access=new URLSearchParams(location.search).get('access');
const message=document.querySelector('#quote-review-message'),review=document.querySelector('#quote-review');
const currency=value=>Number(value||0).toLocaleString('en-US',{style:'currency',currency:'USD'});
const date=value=>value?new Date(`${value}T00:00:00`).toLocaleDateString():'Not specified';
function fail(text){message.textContent=text;message.hidden=false;review.hidden=true}
function render(data){message.hidden=true;review.hidden=false;document.querySelector('#review-quote-number').textContent=`Quote ${data.quote_number}`;document.querySelector('#review-customer').textContent=`Prepared for ${data.customer_first_name||''} ${data.customer_last_name}${data.organization?` — ${data.organization}`:''}`.trim();document.querySelector('#review-status').textContent=data.status;document.querySelector('#review-dates').textContent=`Requested delivery: ${date(data.requested_delivery_date)} · Quote expires: ${date(data.expiration_date)}`;const body=document.querySelector('#review-items');body.replaceChildren();data.items.forEach(item=>{const details=[item.part_number&&`Part ${item.part_number}`,item.brand,item.color,item.size&&`Size ${item.size}`].filter(Boolean).join(' · '),prints=(item.prints||[]).map(print=>`${print.print_location}: ${print.artwork_name}${print.width_inches||print.height_inches?` (${print.width_inches||'?'} × ${print.height_inches||'?'} in.)`:''}`).join('; '),description=[item.description,details,prints&&`Prints: ${prints}`].filter(Boolean).join('\n');const row=document.createElement('tr');[description,item.quantity,currency(item.unit_price),currency(item.line_total)].forEach((value,index)=>{const cell=document.createElement('td');cell.textContent=value;if(index===0)cell.style.whiteSpace='pre-line';row.append(cell)});body.append(row)});['subtotal','discount','shipping','tax','total'].forEach(key=>document.querySelector(`#review-${key}`).textContent=currency(data[key]));let payment=data.payment_option;if(data.payment_option==='Deposit'&&data.deposit_amount)payment+=data.deposit_type==='Percent'?` — ${data.deposit_amount}% required`:` — ${currency(data.deposit_amount)} required`;document.querySelector('#review-payment').textContent=payment;document.querySelector('#review-notes').textContent=data.customer_notes||'No additional notes.';const form=document.querySelector('#quote-response-form');form.hidden=!['Draft','Sent','Changes Requested'].includes(data.status)}
async function loadQuote(){if(!access)return fail('This quote link is incomplete. Please contact JMY for a new link.');try{const response=await fetch(`${quoteBase}/rest/v1/rpc/get_quote_by_token`,{method:'POST',headers:{apikey:quoteKey,'Content-Type':'application/json'},body:JSON.stringify({p_access_token:access})}),data=await response.json();if(!response.ok||!data)return fail('This quote is unavailable or the private link is no longer valid.');render(data)}catch{fail('Unable to reach the secure quote system. Please try again shortly.')}}
document.querySelector('#quote-response-form').addEventListener('submit',async event=>{event.preventDefault();const action=event.submitter?.value;if(!action)return;message.hidden=false;message.textContent=action==='approve'?'Recording your approval…':'Sending your change request…';try{const response=await fetch(`${quoteBase}/rest/v1/rpc/respond_to_quote`,{method:'POST',headers:{apikey:quoteKey,'Content-Type':'application/json'},body:JSON.stringify({p_access_token:access,p_action:action,p_notes:document.querySelector('#response-notes').value.trim()||null})}),data=await response.json();if(!response.ok)throw new Error();message.textContent=action==='approve'?`Thank you. Your quote has been approved. Your invoice number is ${data.invoice_number}. JMY has been notified.`:'Your requested changes have been sent to JMY.';document.querySelector('#quote-response-form').hidden=true;document.querySelector('#review-status').textContent=data.status}catch{message.textContent='Your response could not be saved. Please contact JMY directly.'}});
const renderQuoteView=render;
render=data=>{renderQuoteView(data);const isInvoice=data.status==='Approved'&&data.invoice_number;if(isInvoice){document.querySelector('h1').textContent='Your invoice';document.querySelector('#review-quote-number').textContent=`Invoice ${data.invoice_number}`;document.querySelector('#review-status').textContent='Invoice';document.title=`Invoice ${data.invoice_number} — JMY Fabrication`}document.querySelectorAll('#review-items tr').forEach((row,index)=>{const url=data.items[index]?.mockup_url;if(!url)return;const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener';link.className='mockup-link';link.textContent='View design/mockup';row.cells[0].append(document.createElement('br'),link)})};
document.querySelector('#quote-response-form').addEventListener('submit',event=>{if(event.submitter?.value==='approve')setTimeout(loadQuote,900)});
loadQuote();
